### PR TITLE
V0.11.13 compat

### PR DESCRIPTION
**Pull request by duralog**
based off of @thejinx0r branch. it just needed a one-liner for @mafintosh truncate addition. the rest was just a fix for the incorrect use of HandleScope. it works for me, with both 0.10 and 0.11... though, I didn't actually test everything... just a few quick mounts to make sure it was working...

all the best

### CODE REVIEW

**Comment by epitron** [comment]
Merge please!

**Comment by mafintosh** [comment]
@bcle if you are up for it you can add me as a maintainer on this repo/npm-package and i'll maintain it? :)

**Comment by heavyk** [comment]
+1 torrent-mount won't work on io.js without this... !!!

**Comment by mafintosh** [comment]
@heavyk since this project seems to be dead i've started writing alternate fuse-bindings, https://github.com/mafintosh/fuse-bindings. i'm gonna port torrent-mount to use them as well

**Comment by bcle** [comment]
Sorry for the long delay, guys. I added mafintosh as collaborator and would welcome others.

**Comment by bcle** [comment]
Bumped version and npm published'

**Comment by epitron** [comment]
Playing the fork card always gets results. :)

Thanks!

**Pull request merged**
